name: buildtex

on:
  push:
    branches: main
    paths: [docs/**]
  pull_request:
    branches: main
    paths: [docs/**]
    
permissions:
  contents: write

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps: # from https://github.com/Crowdfeeding/rescue-delivery-capstone/blob/main/.github/workflows/docs.yaml
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          texlive_version: 2024
          run: |
            apk add make
            cd docs
            make

      # Commit and push generated PDFs (from ChatGPT advice)
      - name: Commit and push PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add/Update PDFs from changed LaTeX files'
          file_pattern: 'docs/*.pdf'
          branch: main
